### ISSUE TITLE
Use same boost version like FESA

### ISSUE THREAD

**Issue by alexxcons** [fair-acc/gr-digitizers#21]
In GitLab by @alexxcons on Jan 9, 2019, 16:20

- see branch "UseSameBoosAsFESA"

- Current Problem: FESA uses static linking

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Jan 9, 2019, 16:52

Possibly helps to build boost 1.54.0 (or newer) from source locally and link against it

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Jan 11, 2019, 10:35

Tried the following:
Download and build boost 1.54.0 from source, install it into local directory, link gr-digitizer against it.
Running the unit-tests of gr-digitizer now seg.faults:
```
[JDK8]./lib/test_digitizers_test.sh 

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f2cb704717c in waitpid () from /lib64/libc.so.6
#1  0x00007f2cb6fc4e52 in do_system () from /lib64/libc.so.6
#2  0x00007f2cba8c6439 in TUnixSystem::StackTrace() () from /opt/cern/root/lib/libCore.so
#3  0x00007f2cba8c813c in TUnixSystem::DispatchSignals(ESignals) () from /opt/cern/root/lib/libCore.so
#4  <signal handler called>
#5  0x00007f2cb78d6200 in std::locale::locale(std::locale const&) () from /lib64/libstdc++.so.6
#6  0x00007f2cbd2b7998 in boost::filesystem::path::imbue(std::locale const&) () from /common/home/bel/schwinn/lnx/Software/boost_1.54.0/lib/libboost_filesystem.so.1.54.0
#7  0x00007f2cbd2b7a41 in boost::filesystem::path::codecvt() () from /common/home/bel/schwinn/lnx/Software/boost_1.54.0/lib/libboost_filesystem.so.1.54.0
#8  0x00007f2cbd78e0b8 in gr::prefs::_sys_prefs_filenames() () from /lib64/libgnuradio-runtime-3.7.12.0.so.0.0.0
#9  0x00007f2cbd78e594 in gr::prefs::prefs() () from /lib64/libgnuradio-runtime-3.7.12.0.so.0.0.0
#10 0x00007f2cbd78e714 in gr::prefs::singleton() () from /lib64/libgnuradio-runtime-3.7.12.0.so.0.0.0
#11 0x00007f2cbbf1237a in _GLOBAL__sub_I_udp_source_impl.cc () from /lib64/libgnuradio-blocks-3.7.12.0.so.0.0.0
#12 0x00007f2cbd9edb03 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#13 0x00007f2cbd9df06a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#14 0x0000000000000001 in ?? ()
#15 0x00007ffe1e2cd106 in ?? ()
#16 0x0000000000000000 in ?? ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f2cb78d6200 in std::locale::locale(std::locale const&) () from /lib64/libstdc++.so.6
#6  0x00007f2cbd2b7998 in boost::filesystem::path::imbue(std::locale const&) () from /common/home/bel/schwinn/lnx/Software/boost_1.54.0/lib/libboost_filesystem.so.1.54.0
#7  0x00007f2cbd2b7a41 in boost::filesystem::path::codecvt() () from /common/home/bel/schwinn/lnx/Software/boost_1.54.0/lib/libboost_filesystem.so.1.54.0
#8  0x00007f2cbd78e0b8 in gr::prefs::_sys_prefs_filenames() () from /lib64/libgnuradio-runtime-3.7.12.0.so.0.0.0
#9  0x00007f2cbd78e594 in gr::prefs::prefs() () from /lib64/libgnuradio-runtime-3.7.12.0.so.0.0.0
#10 0x00007f2cbd78e714 in gr::prefs::singleton() () from /lib64/libgnuradio-runtime-3.7.12.0.so.0.0.0
#11 0x00007f2cbbf1237a in _GLOBAL__sub_I_udp_source_impl.cc () from /lib64/libgnuradio-blocks-3.7.12.0.so.0.0.0
#12 0x00007f2cbd9edb03 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#13 0x00007f2cbd9df06a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#14 0x0000000000000001 in ?? ()
#15 0x00007ffe1e2cd106 in ?? ()
#16 0x0000000000000000 in ?? ()
===========================================================
```

Looks like gnuradio itself( via volk) as well uses boost in gr::prefs::_sys_prefs_filenames() ... and it seems to use the boost version installed on the system, which conflict with my local 1.54.0.

There is a gnuradio issue to get rid of this boost dependency:
https://github.com/gnuradio/volk/issues/174
However I dont expect it to get solved soon / to get it released / to get IN to install the new release.

We could ask FESA to provide a fully blown boost installation in /opt/gsi/3rdparty/boost and than later ask IN to build the installed gnuradio against it ... but I doubt that any of both would agree.

Another "solution" would be, to hope for a more recent boost on the next development cluster (asl75x), used by FESA and gnuradio.

... actually I wonder why The FESA deploy-Unit is running fine. I would expect it to crash the same way than the unit-test does.

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Nov 1, 2019, 15:07

closed

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Nov 1, 2019, 15:09

closed as wontfix.  

Statically linking FESA against boost 1.69 and at the same time dynamically linking gnuradio with the system installed boost seems to be the only valid way to get things to run fine.
