### ISSUE TITLE
Seg.Fault when starting FESA class on dal006

### ISSUE THREAD

**Issue by alexxcons** [fair-acc/gr-digitizers#40]
In GitLab by @alexxcons on Mar 5, 2019, 12:44

backtrace does not help at all:

> [Switching to Thread 1979]  
> 0x00007fffedc57da5 in ?? ()  
> (gdb) bt  
> #0  0x00007fffedc57da5 in ?? ()  
> DigitizerClass2#1  0x00007fffedc3dd5b in ?? ()  
> DigitizerClass2#2  0x0000000000000033 in ?? ()  
> DigitizerClass2#3  0x000000000000001a in ?? ()
> DigitizerClass2#4  0x000000000000ffff in ?? ()  
> DigitizerClass2#5  0x00007fffce908f6a in ?? ()  
> DigitizerClass2#6  0x00007fffc8009650 in ?? ()  
> DigitizerClass2#7  0x00007ffff304184c in ?? ()  
> DigitizerClass2#8  0x00007fffc8010203 in ?? ()  
> DigitizerClass2#9  0x0000000000000033 in ?? ()  
> DigitizerClass2#10 0x00007fffce908de0 in ?? ()  
> DigitizerClass2#11 0x00007ffff38ffecd in ?? ()  
> DigitizerClass2#12 0x00007fffedfbbb88 in ?? ()  
> DigitizerClass2#13 0x000000000000001a in ?? ()  
> DigitizerClass2#14 0x00007fffce908de0 in ?? ()  
> DigitizerClass2#15 0x00007ffff395eab9 in ?? ()  
> DigitizerClass2#16 0x00007fffc8013430 in ?? ()  
> DigitizerClass2#17 0x00007fffc8009650 in ?? ()  
> ....

The management console spits some errors:
![HardwareBugP6000](https://my-gitlab-bucket.s3.amazonaws.com/406695439/2905fe13b827e9b93b777fe87763b79f.jpg)

According to this thread, we possibly require a more recent kernel:
http://forums.debian.net/viewtopic.php?t=117061

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:45

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:45

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:46

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:48

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:49

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:50

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:55

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 12:58

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 13:34

Crash can be reproduced on dal004. As soon as more than one p6000 is plugged in, the crash occurs (sometimes it just gets stuck, sometimes it crashes. Always same errors on management console)
It does not matter if the second 6000 scope is wired via gnuradio. As soon as it is plugged in, the software will fail. ( So it looks like this is not a gnuradio problem, but rather some general USB bus problem)

A p3000 together with a p6000 runs fine. (Error on management console as well shown, but runs fine)

In order to reproduce the crash, check 2x6000.crash.grc in dal004 folder.

TODO: Test if a more recent kernel fixed the problem.

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 5, 2019, 14:13

changed the description

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 12, 2019, 11:56

Cannot test properly on local computer --> no USB3 Port!

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 12, 2019, 15:27

assigned to @alexxcons

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 19, 2019, 14:50

moved from DigitizerClass2#64

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 19, 2019, 14:50

mentioned in commit 2c61609b43e177f96a79834a08c1f1b33e2ffa5d

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 19, 2019, 14:55

A bug in the ps6000 firmware/library "ps6000OpenUnit" brings the software sometimes to crash, sometimes to get stuck.
Bug is only triggered when a ps6000 scope is addressed by its serial number, any does not happen for all ps 6000 scopes.

As workaround, always all available ps6000 scopes are discovered, the serial-number matching is done in software, afterwards all non-matching ps6000 scopes are released.

**Comment by alexxcons** [comment]
In GitLab by @alexxcons on Mar 19, 2019, 14:55

closed
